### ISSUE TITLE
Event listeners

### ISSUE THREAD

**Issue by ilicmarko** [lazarljubenovic/fucking-dollar#1]
Add an `on` or `bind` method to add event listeners and you will cover 90% of jQuery use case.

Something along these lines:
```js
Node.prototype.on = window.on = Node.prototype.addEventListener;

NodeList.prototype.on = NodeList.prototype.addEventListener = (name, fn) => {
     Array.prototype.slice.call(this).forEach((elem) => {
         elem.addEventListener(name, fn, false);
     });
}
```
Also an `off` method is useful.

I don't know if this is the idea of this repo or just making typed selectors :laughing:

**Comment by lazarljubenovic** [comment]
Thanks for the fucking suggestion, but I ain't messing with fucking prototypes. TC39 would find me and fucking skin me alive. `on(el, name, fn)` would be fine, but that's not a fucking dollar, that's a fucking `on`. This repo is for fucking dollars.
